<?php   $auth = Zend_Auth::getInstance();
        if ($auth->hasIdentity()) :
?>
<p><a href="<?php echo $this->url(array('controller'=>'post', 'action'=>'sign')); ?>">Write a new post</a></p>
<?php else : ?>
<p>Please <a href="<?php echo $this->url(array('controller'=>'auth', 'action'=>'index')); ?>">login</a> to continue.</p>
<p>Click <a href="<?php echo $this->url(array('controller'=>'auth', 'action'=>'signup')); ?>">here to sign up!</a></p>
<?php endif; ?>
 
Welcome to Tweets! Showing latest posts: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <dt><a href="<?php echo $this->baseUrl(); ?>/post/userposts?userid=<?php echo $entry->userid; ?>"><?php echo $this->escape($entry->username) ?></a> - <?php echo $this->escape($entry->created) ?></dt>
    <dd><?php echo $this->escape($entry->post) ?></dd>
    <?php endforeach ?>
</dl>
