<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Tweets! by JP</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
	<?php echo $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js'); ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>Tweets! by JP</b>
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(
            array('controller'=>'post'),
            'default',
            true) ?>">Posts</a>
    </div>
		<div id="login"><div id="logged-in-as">
				<?php echo $this->loggedInAs(); ?> </div>
		</div>
</div>
<?php print var_dump($_COOKIE); ?>
<?php echo $this->layout()->content ?>
 
</body>
</html>