<p><a href="<?php echo $this->url(
    array(
        'controller' => 'post',
        'action'     => 'sign'
    ),
    'default',
    true) ?>">Write a new post</a></p>
 
All posts: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <dt><a href="<?php echo $this->baseUrl(); ?>/post/userposts?userid=<?php echo $entry->userid; ?>"><?php echo $this->escape($entry->username) ?></a> - <?php echo $this->escape($entry->created) ?></dt>
    <dd><?php echo $this->escape($entry->post) ?></dd>
    <?php endforeach ?>
</dl>
